---
title: "Orquídeas en Costa Rica"
output: html_document
---

```{r message=FALSE, warning=FALSE}
library(sf)
library(raster)
library(dplyr)
library(spData)
library(leaflet)
library(plotly)
library(DT)
library(tidyr)

```

# Carga de datos
```{r}
orquideas <-
  st_read(
    "https://raw.githubusercontent.com/gf0604-procesamientodatosgeograficos/2021i-datos/main/gbif/orchidaceae-cr-registros.csv",
    options = c(
      "X_POSSIBLE_NAMES=decimalLongitude",
      "Y_POSSIBLE_NAMES=decimalLatitude"
    ),
    quiet = TRUE
  )
```


```{r}
areasp <-
  st_read(
    "https://raw.githubusercontent.com/gf0604-procesamientodatosgeograficos/2021i-datos/main/sinac/asp/asp-wgs84.geojson",
    quiet = TRUE
  )
```

# Establecemos el sistema de coordenadas
```{r}
st_crs(orquideas) = 4326
st_crs(areasp) = 4326
```


```{r}
orquideas <- orquideas %>%
  filter(!is.na(coordinateUncertaintyInMeters) & coordinateUncertaintyInMeters <= 1000)
```


```{r}
orquideas <- orquideas  %>% filter(!is.na(species))
```

```{r}
areasp <- areasp %>%
  filter(descripcio!="Area Marina de Manejo" & descripcio!="Area marina protegida")
```


```{r message=FALSE, warning=FALSE}
areasp_registros <-
  areasp %>%
  sf::st_make_valid() %>%
  sf::st_join(orquideas) %>%
  group_by(nombre_asp) %>%
  summarize(especies = n_distinct(species,na.rm = TRUE))
```

```{r}
st_crs(areasp_registros) = 4326
```

# Paleta de colores
```{r}

col_regis <-
  colorNumeric(palette = "PuRd",
               domain = areasp_registros$especies,
               na.color = "transparent")

```

```{r}
col_espe <-
  colorNumeric(palette = "YlOrRd",
               domain = areasp_registros$especies,
               na.color = "transparent")
```



# Mapa Leaflet
```{r}
leaflet() %>%
  addTiles(group = "OSM") %>%
  addPolygons(
    data = areasp_registros,
    fillColor = ~ col_espe(areasp_registros$especies),
    fillOpacity = 0.7,
    stroke = TRUE,
    color = "black",
    weight = 1,
    popup = paste(
      paste(
        "<strong>Provincia:</strong>",
        areasp_registros$nombre_asp
      ),
      paste(
        "<strong>Cantidad de especies:</strong>",
        areasp_registros$especies
        
      ),
      sep = '<br/>'
    ),
    group = "Provincias - especies"
  ) %>%
  addLayersControl(baseGroups = c("OSM"),
                   overlayGroups = c("Provincias - especies")) %>%
  addLegend(
    position = "bottomleft",
    pal = col_espe,
    values = areasp_registros$especies,
    group = "Provincias - especies",
    title = "Cantidad de orquideas")      

```